version: '2'

services:

  app:
    build:
      context: .
    hostname: app
    links:
      - redis
    environment:
      - redis_dsn=$redis_dsn
      - cache_ttl=$cache_ttl
      - gmaps_backend_api_key=$gmaps_backend_api_key
      - gmaps_frontend_api_key=$gmaps_frontend_api_key
    ports:
      - "85:80"

  redis:
    image: redis:4-alpine
    hostname: redis
    volumes:
      - ./redis:/data
